### ISSUE TITLE
Re-trying request until successful

### ISSUE THREAD

**Issue by cannyboy** [Legoless/AFNetworking-RACRetryExtensions#1]
I'm trying to figure out the pattern I should use with RACRetryExtensions to do the following: https://github.com/AFNetworking/AFNetworking/issues/2622

Is it possible?

**Comment by Legoless** [comment]
That depends on the exact API functionality. If API returns HTTP 2xx status even when it is "not completed", this method will not retry, because `AFNetworking` must return an error - either status different from 2xx or parse error, or network error. This would require modification to `RACRetryExtensions` code, but you are free to modify the code and use it.

However, if you get 4xx status from your API call, then it would be possible to achieve this with `RACRetryExtensions`. This is doable by providing your own `retryBlock` parameter, which enables you to do this. Write this block so if the 4xx status is returned in `NSError` and your API returns status not connected, then block returns `YES` for retrying. As for doing it until it is successful, there is a retry limit which you can set, for now you can use `INT_MAX` or another very large number, which will in practice retry for quite a while.

**Comment by cannyboy** [comment]
Thanks. It looks like I get a 200 "OK", with this JSON:
    
    {
      "status": "not completed"
    }
... so I'm guessing I would need to dig into the `RACRetryExtension` code (or possibly convince AFNetworking that having the above response indicates failure).

**Comment by Legoless** [comment]
Yes, the easiest way would be to go into `RACURLSessionRetryDataTask` and modify the code in the last function. You can easily find where retry block is evaluated. Before this evaluation there is a check that error must exist. In your case, you can modify the code to do the `retryBlock` check before checking for error, since there is no error in your case. That way you can define retries even with successful response.

**Comment by cannyboy** [comment]
Thanks, I'll give that a go. Probably do something like this:

    BOOL retryTest = YES;
            
     if (self.testBlock) {
        retryTest = self.testBlock(response, responseObject, error);
    }
            
    if (responseObject) {
        if ([responseObject isKindOfClass:[NSDictionary class]]) {
            if (responseObject[@"status"]) {
                if (![(NSString*)responseObject[@"status"] isEqualToString:@"completed"]) {
                    retryTest = YES;
                }
            }
        }
    }

I'm actually still a bit confused on how to use `RACRetryExtensions`, probably because I'm unfamiliar with `ReactiveCocoa`. Usually, AFNetworking has success and failure blocks, with success being passed the responseObject. I'm guessing I get this in `subscribeNext:`?

**Comment by Legoless** [comment]
Yes, the success object is passed at next methods when subscribed. You can also subscribe to listen to errors, where you get `NSError` objects. ReactiveCocoa uses signals to chain operations in a pipeline. I suggest you do a quick read of the basics, just so you know what is going on.
